### ISSUE TITLE
snippet-enumerator.js needs to look for .code-snippets in lines 50-55

### ISSUE THREAD

**Issue by RandalSchwartz** [abulka/vscode-snippets-explorer#10]
Without that, the extension robert-brunhage.flutter-riverpod-snippets does not have its snippets "explored", even though they are active in the editor.

**Comment by abulka** [comment]
I wonder:
- Is there a standard naming convention for the directory name containing snippets. Currently only the `snippets` directory is scanned by my extension. 
- Is the directory name `.code-snippets` a commonly used name or unique to `flutter-riverpod-snippets`?  
- Should I be looking for a list of other common directory names containing snippets?

**Comment by abulka** [comment]
Solved by #11 

`.code-snippets` files are now scanned for snippets.
