### ISSUE TITLE
Extension does not show up 'global' user snippets

### ISSUE THREAD

**Issue by JanKochEmpiriecom** [abulka/vscode-snippets-explorer#11]
I created some global user snippets with the vscode build in method (Settings gear icon -> User snippets -> New global snippets file). They get created in my home folders library with names like "jest.code.snippets" or "gql.code-snippets". All snippest have the scope ""scope": "typescript,typescriptreact",".

I hited refresh many times, restarted vscode but non of the snippets appear in Snippet Explorer.

Could you please tell me how to handle global user snippets?

**Comment by abulka** [comment]
Global User Snippets are currently not supported. I didn't even know such snippets existed - I wonder how new they are?

There are five snippet locations that are scanned:
- Project Snippets
- User Snippets
- Extension Snippets
- Built in Extension Snippets
- In the `data` directory underneath the vscode app (portable mode)
- `TODO` Global User Snippets (found in `~/Library/Application Support/Code/User/snippets/` which is the same location as language specific snippets with `.json` extensions except that global user snippets have arbitrary user defined file names and the `.code-snippets` file extension).

which are documented in my [snippet locations](https://github.com/abulka/vscode-snippets-explorer/blob/master/docs/finding_snippets_doco.md) developer notes.

I'll look at enhancing this extension and adding `Global User Snippets`.

**Comment by abulka** [comment]
@JanKochEmpiriecom I have been working on a new version, if you are interested in testing a beta version, please let me know. I would supply a `.vsix` file which you can install via the `vscode / extensions / install from vsix...`.

**Comment by abulka** [comment]
Here is the beta release https://github.com/abulka/vscode-snippets-explorer/releases/tag/v1.0.6

**Comment by abulka** [comment]
V1.0.6 has been officially released which displays global user snippets.  Vscode should auto-update to the new version.
