### ISSUE TITLE
User snippets in portable VSCode installation are not discovered on Win 10

### ISSUE THREAD

**Issue by wikiped** [abulka/vscode-snippets-explorer#9]
When Visual Studio Code is used in portable mode it stores User Settings under `data` folder within its installation directory.

I.e. on Windows 10:

`D:\SomeCustomFolder\Visual Studio Code\data\user-data\User\snippets\`

It looks like this directory is not scanned by snippets-explorer (it shows no snippets).

**Comment by abulka** [comment]
Interesting - presumably the plugin could look where it (the executable) is running from and look for `data\user-data\User\snippets\`. Presumably the executable is in `D:\SomeCustomFolder\Visual Studio Code\`?

**Comment by wikiped** [comment]
Correct. Path to executable would be:
`D:\SomeCustomFolder\Visual Studio Code\Code.exe`

All user specific stuff is under `D:\SomeCustomFolder\Visual Studio Code\data\` folder.

**Comment by abulka** [comment]
Please try 1.0.4 of this extension - unzip it and manually install via 
![image](https://user-images.githubusercontent.com/11467530/125257064-65302c00-e340-11eb-8706-95f05778188c.png)

[snippets-explorer-1.0.4.vsix.zip](https://github.com/abulka/vscode-snippets-explorer/files/6799838/snippets-explorer-1.0.4.vsix.zip)

If it works, I'll publish onto the marketplace.

**Comment by wikiped** [comment]
Thank you very much. 
Tested with latest VSCode 1.58.2 and and it works fine. Although it seems like to actually see the snippets in the explorer window you have to open a file with relevant extension. I.e. to see javascript snippets you have to have `some.js` file opened in editor. Anyways once the file is opened snippets (both builtin and user-defined) are shown and clicking on a snippet inserts it to opened file.

Thanks again for adding this feature.

**Comment by abulka** [comment]
Glad it worked. Have now officially released 1.0.4.

Re the snippets are only shown when you open a file of that type - that behaviour is normal / as designed.
